#!/bin/zsh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice


################  FCITX ################
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim

killall fcitx
fcitx &

########################################

#export GTK_IM_MODULE=ibus
#export XMODIFIERS="@im=ibus"
#export QT_IM_MODULE=ibus
# export QT_IM_MODULE=xim

#killall ibus
#killall ibus-daemon
#ibus-daemon -d -x

#######################################

# wice-client &

# set CapsLk as Ctrl, and Ctrl_L as Super_L
xmodmap ~/.Xmodmap 2>/dev/null

dropboxd &

wmname LG3D

# exec awesome
DEFAULT_SESSION=awesome
case $1 in
  awesome) exec awesome ;;
  wmii) exec wmii ;;
  openbox) exec openbox-session;;
  # xmonad) exec xmonad ;;
  *) exec $DEFAULT_SESSION ;;
esac
